config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true

  CUTENESS = [ "Mehh", "A little", "Cute!", "OMG!!!"]
  SOFTNESS = [ "So rough", "Could use a brushing", "Fluffy!"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :error, :success
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Meow! There's one more kitten!"
      redirect_to @kitten
    else
      flash.now[:error] = "Bark! Kitten details submitted incorrectly"
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = "Meow! You edited a kitten!"
      redirect_to @kitten
    else
      flash.now[:error] = "Bark! Kitten details submitted incorrectly"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy
    flash[:success] = "You released a kitten into the wild!"
    redirect_to root_path, status: :see_other
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_details.html.erb
Age: <%= kitten.age %><br>
Cuteness: <%= kitten.cuteness %><br>
Softness: <%= kitten.softness %><br>
<%= button_to "Edit", edit_kitten_path(kitten), method: :get %>
<%= button_to "Release Kitten", kitten_path(kitten), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/kittens/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %><br>
<%= f.label :age, "Age" %>
<%= f.select :age, (0..20).to_a %><br>
<%= f.label :cuteness, "Cuteness" %>
<%= f.select :cuteness, Kitten::CUTENESS %><br>
<%= f.label :softness, "Softness" %>
<%= f.select :softness, Kitten::SOFTNESS %><br>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= form_with model: @kitten do |f| %>
  <%= render 'form', f: f%>
  <%= submit_tag "Finish Editing" %>
<% end %>
<%= button_to "Release Kitten", kitten_path(@kitten), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= button_to "Go Back", kittens_path, method: :get %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<%= button_to "Add A Kitten", new_kitten_path, method: :get %>

<% @kittens.each do |kitten| %>
  Name: <%= kitten.name %><br>
  <%= render 'details', kitten: kitten %>
<% end %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= form_with model: @kitten do |f| %>
  <%= render 'form', f: f%>
  <%= submit_tag "Add a Kitten" %>
<% end %>
<%= button_to "Go Back", kittens_path, method: :get %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<%= render 'details', kitten: @kitten %>
<%= button_to "Go Back", kittens_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>